### ISSUE TITLE
Site breaks if you load / while logged in

### ISSUE THREAD

**Issue by maxlemieux** [cwalker226/Cangaroo#57]
_http_outgoing.js:535
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:535:11)
    at ServerResponse.header (/Users/max/Cangaroo/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/Users/max/Cangaroo/node_modules/express/lib/response.js:170:12)
    at done (/Users/max/Cangaroo/node_modules/express/lib/response.js:1008:10)
    at Immediate._onImmediate (/Users/max/Cangaroo/node_modules/express-handlebars/lib/utils.js:26:4)
    at processImmediate (internal/timers.js:456:21) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by maxlemieux** [comment]
Missing return statement from responses. Adding 'return' fixed it.
